services:
  - type: web
    name: grupanya-task-test-api
    env: node
    rootDir: apps/api
    plan: free
    buildCommand: npm ci && npm run build && npx prisma migrate deploy --schema prisma/schema.prisma
    startCommand: npm run start
    autoDeploy: true
    envVars:
      - key: DATABASE_URL
        value: SET_IN_DASHBOARD
      - key: DISABLE_JOBS
        value: "true"
      - key: CORS_ORIGINS
        value: "*"

  - type: web
    name: grupanya-task-test-web
    env: node
    rootDir: apps/web
    plan: free
    buildCommand: |
      cd ../..
      npm ci
      npm --workspace=packages/ui run build
      npm --workspace=packages/sdk run build
      cd apps/web
      npm run build
    startCommand: npm run start
    autoDeploy: true
    envVars:
      - key: NEXT_PUBLIC_API_BASE
        value: https://grupanya-task-test-api.onrender.com/api
      - key: NEXT_PUBLIC_DEV_USER_ID
        value: public-viewer
      - key: NEXT_PUBLIC_DEV_ROLE
        value: MANAGER

databases: []
