services:
  - type: web
    name: grupanya-api
    env: node
    rootDir: apps/api
    plan: free
    buildCommand: npm ci && npm run build && npx prisma migrate deploy --schema prisma/schema.prisma
    startCommand: npm run start
    autoDeploy: true
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: grupanya-postgres
          property: connectionString
      - key: REDIS_URL
        fromService:
          name: grupanya-redis
          type: redis
          property: connectionString
      - key: DISABLE_JOBS
        value: "true"
      - key: CORS_ORIGINS
        value: "*"

databases:
  - name: grupanya-postgres
    databaseName: grupanya_task
    plan: free

redis:
  - name: grupanya-redis
    plan: free

